// <auto-generated />
using CarRentalApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRentalApp.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20190715091809_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.Property<string>("LicensePlate")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<bool>("HasAutomaticGearbox");

                    b.Property<string>("Model");

                    b.Property<short>("NrOfDoors");

                    b.Property<short>("NrOfSeats");

                    b.Property<float>("PricePerDay");

                    b.HasKey("LicensePlate");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
